### ISSUE TITLE
Writable sensors - transfer of measured values

### ISSUE THREAD

**Issue by Alex-github-acc** [Tidone/homeassistant_eta_integration#15]
Good morning Tidone,

as a ‘non computer scientist’ I have once again reached my limits ... and need your valued help.

I have underfloor heating that I would like to control with the ETA control unit.
For this purpose, I have created the rooms in the ETA and also external, writable interfaces for 
the room in the Modbus/TCP
![image](https://github.com/user-attachments/assets/a15849c2-b401-456a-9b81-a39af7a05f00)

Then for the:
- temperature sensors
- setpoint temperature and 
- setback temperature
... the the writeable sensors in my heating control system ... looks in ETA-Control like this:
![image](https://github.com/user-attachments/assets/44dd6bd7-beed-49f8-a27b-1eed26ba8166)

For the room temperature there are two hints from ETA:
![image](https://github.com/user-attachments/assets/77f939be-034f-4d43-ab00-7da62cdda1d6)
![image](https://github.com/user-attachments/assets/c212ecde-7630-46e6-b0c6-8f7461480a9d)

With your great integration, I also get this as an entity in HA: 
![image](https://github.com/user-attachments/assets/cf9bcd6f-dda5-4663-9a1e-25afee3154b5)

The current room temperature i get via Zigbee thermostats:
![image](https://github.com/user-attachments/assets/691ea3e9-1366-452c-9d3e-337d0e3b0b3f)

... I am also very proud of myself that I have found a way to set the value of a temperature sensor there.
(... Automation --> Action --> ETA sensor ‘Set value’)
![image](https://github.com/user-attachments/assets/f85bfb4b-9c4f-4e2c-89d6-0c539517bce3)

**Obs.:** _Perhaps this could also be done via a template or skript?
               But I don't know enough about that. --> Every hint is welcome :-)_

Anyway - for the action in the automation it looks like this:
![image](https://github.com/user-attachments/assets/1ecf96b0-72c0-4f0f-89e1-60c1e0b3d425)

if I execute this action (manually), the value of the Zigbee temperature sensor (here 17.01 °C) is adopted 
and also appears in the ETA integration
... but too small by a factor of 10 :-( 

![image](https://github.com/user-attachments/assets/ef408eb0-40c9-4d4f-8c40-daf9e1f089c1)
and here it is not displayed at all:
![image](https://github.com/user-attachments/assets/52e91d4d-5add-4565-a150-403980ac0f4e)

What am I doing wrong?

**Comment by Tidone** [comment]
Hi Alex,

Sorry for the late reply.

You are using the wrong service to set the value of the writable sensor.
You should use `number.set_value` instead of `eta_webservice.set_value`:

![Bildschirmfoto zu 2024-09-23 11-44-00](https://github.com/user-attachments/assets/2b3b92e9-c2b0-44cc-a018-5da848ac2a58)
or in YAML editor:
![Bildschirmfoto zu 2024-09-23 11-42-26](https://github.com/user-attachments/assets/4e2ae247-be58-4120-866b-986215dcc473)

The problem here is that the ETA API uses some weird format to set sensor values. For some sensors you can set the value directly, and for other sensors you have to scale the value by 10, 100, or even some other value.

The `number.set_value` service will do that for you, and you can just set the desired value as is.

The `eta_webservice.set_value` service on the other hand, is meant as a very low-level service you can use if you want to set a sensor value even if the integration can't detect the sensor. That's why you have to specify the endpoint URL instead of the actual HA sensor entity, and you have to do the scaling yourself and provide the raw value.

**Comment by Alex-github-acc** [comment]
Dear Tidone,

Thank you for another quick and competent reply.

As the actual values (which I receive via Z2M devices) are constantly changing, this cannot be done in the UI.  

In YAML it now looks like this for me:
![image](https://github.com/user-attachments/assets/3ba349f4-de8e-472d-8ed5-61416d8fc181)

Once again my sincere thanks, Alex
