### ISSUE TITLE
Change of IP-address

### ISSUE THREAD

**Issue by threadstone83** [Tidone/homeassistant_eta_integration#7]
Hello,

I have to change the IP of my ETA Pellets Unit. Is there any possibility to change the IP in the integration or do I have to set up the integration completely new?

Best regards
Andreas

**Comment by Tidone** [comment]
Hi,

It is not possible to change the connection settings via the UI. I took a look at other integrations and none of them provide this feature, so I didn't implement it.

Soma background info:
Unfortunately it is a bit complicated to change the IP address because all entities use the IP address as part of their internal id. I don't know what HA will do with the entities if you change the IP address. Maybe it renames their id without problems, maybe it duplicates every sensor, or maybe it even refuses to start the integration.

You can try to manually change the IP in the settings file.
To do this, follow these steps:
1. Shut down HA
2. Open the HA folder and go to the `.storage` subfolder
3. Edit the file `core.config_entries`
    -  Search for the ETA integration entry. It should be the one with the `eta_webservices` domain
    - Change the `host` entry (and nothing else)
4. Save the file and start HA again

I think the best solution whithout the risk of breaking anything is to just add a new eta device and remove the old one. You can open the device page of the old one in a new window to see which sensors you have to add.

**Comment by threadstone83** [comment]
What a pity but I understand the problem. I think I will change the IP of my ETA device, delete the integration and add it new. 
I don't know how I could do the other way because I have installed HA in a VM on my Synology and I don't know how to access the storage 🙈
Thank you for your help!
